version: '3.1'
services:
  database:
    image: postgres:16-alpine
    ports:
      - 2023:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
  server:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - database
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
    ports:
      - 2024:${PORT}
